apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: beta-shinchoku-net-tls
  namespace: default
spec:
  secretName: beta-shinchoku-net-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: beta.shinchoku.net
  dnsNames:
  - beta.shinchoku.net
